name: mamicheckapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  http: ^0.13.6
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  collection: ^1.19.1
  fl_chart: ^1.0.0
  flutter_native_splash: ^2.4.6
  shared_preferences: ^2.5.3
  flex_color_picker: ^3.7.1
  flutter_local_notifications: ^18.0.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#ECDBF2"
  image: assets/splash/mamichecklogo.png
  android_12:
    color: "#ECDBF2"
    image: assets/splash/mamichecklogo.png